## PROLOGUE — "The Night It All Began" (ليلة البداية)
## In-media-res escape: battered Tito runs the Syndicate cordon through a
## storm-drowned Cairo-inspired metropolis, ending on a rooftop duel with
## his corrupt mentor EL-GHORAB (The Raven). Chains into Chapter 1
## (levels/cairo_night.tscn) after the flatline outro.
##
## Segment map (x left->right):
##   S1  -10..16  alley: movement basics + crawl-under shutter + siren dread
##   S2   16..34  dojo: two light thugs (punch tutorial)
##   S3   34..52  traffic: shield enforcer — frontal immune, hit his back
##   S4   52..84  denial: smoke-launcher + red-line tactical agent -> canopy route
##   S5   84..104 barricade: wipe the squad -> the gate breaches
##   SC  105..112 scaffold zigzag up to the rooftop
##   RF  112..146 stormy roof: girders y=12, floodlights, EL-GHORAB duel
##
## Renderer honesty: this is GL Compatibility — no volumetrics/SSR/SDFGI.
## Rain = CPUParticles3D streaks; smog = exp fog + tinted parallax; lamp
## cones = unshaded translucent meshes; PBR = albedo+normal+roughness stacks
## generated by tools/gen_prologue_art.py. All architecture is real 3D mesh.
extends Node3D

const PRO := "res://assets/textures/prologue/"
const CAIRO := "res://assets/textures/cairo/"
const FONT_BOLD := "res://assets/fonts/DejaVuSans-Bold.ttf"
const ENEMY: PackedScene = preload("res://legacy3d/enemies/enemy.tscn")
const SHIELD := preload("res://legacy3d/enemies/shield_enforcer.gd")
const AGENT := preload("res://legacy3d/enemies/tactical_agent.gd")
const LAUNCHER := preload("res://legacy3d/enemies/smoke_launcher.gd")
const CHECKPOINT: PackedScene = preload("res://legacy3d/world/checkpoint.tscn")
const DEATHZONE: PackedScene = preload("res://legacy3d/world/deathzone.tscn")
const TITO: PackedScene = preload("res://legacy3d/player/tito.tscn")
const PARALLAX := preload("res://legacy3d/world/parallax_layer.gd")

const ARENA_MIN := 117.0
const ARENA_MAX := 143.0
const CHAPTER_ONE := "res://legacy3d/levels/cairo_night.tscn"

# user-supplied dialogue, verbatim (AR + EN)
const LINES_INTRO := [
	["الغراب", Color(0.95, 0.38, 0.22),
		"«فاكر نفسك هتهرب؟ أنت خلاص كرت واتحرق يا تيتو... أنا اللي عملتك، وأنا اللي هنهيك.»",
		"You think you can run? You're a burned card, Tito... I made you, and I am the one putting you down.", 6.2],
	["تيتو", Color(0.55, 0.85, 1.0),
		"«أنا كنت بدفع تمن غلطاتي... بس تمن وسختك هتدفعه دلوقتي يا غراب!»",
		"I was paying for my own mistakes... but you're paying for your filth right now, Ghorab!", 5.6],
]
const LINES_OUTRO := [
	["تيتو", Color(0.9, 0.9, 0.95),
		"«عشان تفهم النهاية... لازم ترجع لليوم اللي كل حاجة بدأت فيه.»",
		"To understand the end... you have to return to the day it all began.", 6.4],
]

var _mats: Dictionary = {}
var _tito: Node3D
var _boss: GhorabBoss
var _gate: StaticBody3D
var _gate_lamp: MeshInstance3D
var _squad_alive := 0
var _intro_done := false
var _outro_started := false

# weather / cinematic state
var _storm: DirectionalLight3D
var _flash_quad: MeshInstance3D
var _bolt_timer := 4.0
var _flash := 0.0
var _siren_t := 0.0
var _siren_red: MeshInstance3D
var _siren_blue: MeshInstance3D
var _siren_light: OmniLight3D
var _cine: CanvasLayer
var _cine_root: Control
var _spk: Label
var _line_ar: Label
var _line_en: Label
var _white: ColorRect
var _black: ColorRect
var _ecg: Line2D
var _ecg_t := -1.0
var _ecg_vals: PackedFloat32Array = []


func _ready() -> void:
	randomize()
	_build_materials()
	_build_environment()
	_build_weather()
	_build_parallax_backdrop()
	_build_street()
	_build_s1_alley()
	_build_s2_dojo()
	_build_s3_traffic()
	_build_s4_denial()
	_build_s5_barricade()
	_build_scaffold_and_roof()
	_build_cinematic_overlay()
	_build_gameplay()
	_build_labels()


# ------------------------------------------------------------ materials --
func _std(c: Color) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = c
	m.roughness = 0.95
	return m


func _glow(c: Color) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	m.albedo_color = c
	return m


func _pbr(base: String, u := 6.0, v := 3.0) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_texture = load(PRO + base + ".png") as Texture2D
	m.normal_enabled = true
	m.normal_texture = load(PRO + base + "_n.png") as Texture2D
	m.roughness = 1.0
	m.roughness_texture = load(PRO + base + "_r.png") as Texture2D
	m.uv1_scale = Vector3(u, v, 1.0)
	return m


func _tex_mat(path: String, tint: Color, unshaded := true, alpha := false) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_texture = load(path) as Texture2D
	m.albedo_color = tint
	if unshaded:
		m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
		m.cull_mode = BaseMaterial3D.CULL_DISABLED
	if alpha:
		m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	return m


func _build_materials() -> void:
	_mats["brick"] = _pbr("wall_brick", 9.0, 4.0)
	_mats["asphalt"] = _pbr("asphalt_wet", 14.0, 4.0)
	_mats["shutter"] = _pbr("shutter", 2.0, 2.0)
	_mats["roof"] = _pbr("roof_concrete", 10.0, 4.0)
	_mats["steel"] = _std(Color(0.16, 0.18, 0.24))
	_mats["dark"] = _std(Color(0.04, 0.045, 0.08))
	_mats["sand"] = _std(Color(0.45, 0.38, 0.27))
	_mats["barrier_w"] = _std(Color(0.85, 0.85, 0.88))
	_mats["barrier_r"] = _std(Color(0.75, 0.12, 0.12))
	_mats["win_lit"] = _glow(Color(0.95, 0.75, 0.4))
	_mats["win_dark"] = _std(Color(0.06, 0.07, 0.12))
	_mats["siren_r"] = _glow(Color(1.0, 0.12, 0.12))
	_mats["siren_b"] = _glow(Color(0.15, 0.35, 1.0))
	_mats["lamp_head"] = _glow(Color(1.0, 0.75, 0.4))
	_mats["gate_g"] = _glow(Color(0.15, 1.0, 0.35))
	# storm-tinted reused cairo backdrop art
	_mats["sky"] = _tex_mat(CAIRO + "sky.png", Color(0.45, 0.52, 0.7))
	_mats["far"] = _tex_mat(CAIRO + "skyline_far.png", Color(0.5, 0.56, 0.75), true, true)
	_mats["mid"] = _tex_mat(CAIRO + "skyline_mid.png", Color(0.5, 0.55, 0.72), true, true)
	# lightning wash sheet (starts invisible)
	var fq := _glow(Color(0.9, 0.94, 1.0, 0.0))
	fq.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	_mats["flash"] = fq
	# fake volumetric cones
	var cone := _glow(Color(1.0, 0.8, 0.45, 0.14))
	cone.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	cone.cull_mode = BaseMaterial3D.CULL_DISABLED
	_mats["cone"] = cone
	var beam := _glow(Color(1.0, 0.2, 0.15, 0.28))
	beam.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	beam.cull_mode = BaseMaterial3D.CULL_DISABLED
	_mats["beam"] = beam


# ---------------------------------------------- environment, weather ----
func _build_environment() -> void:
	var env := Environment.new()
	env.background_mode = Environment.BG_COLOR
	env.background_color = Color(0.03, 0.045, 0.09)
	env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.ambient_light_color = Color(0.16, 0.2, 0.34)
	env.ambient_light_energy = 0.55
	env.fog_enabled = true
	env.fog_mode = Environment.FOG_MODE_EXPONENTIAL
	env.fog_density = 0.016  # the smog is thick tonight
	env.fog_light_color = Color(0.08, 0.1, 0.2)
	env.tonemap_mode = Environment.TONE_MAPPER_ACES
	var we := WorldEnvironment.new()
	we.environment = env
	add_child(we)

	# cold steel-blue storm light; lightning rides on top of this base
	_storm = DirectionalLight3D.new()
	_storm.light_color = Color(0.55, 0.62, 0.9)
	_storm.light_energy = 0.35
	_storm.rotation = Vector3(-0.7, 0.4, 0.0)
	_storm.shadow_enabled = true
	_storm.directional_shadow_max_distance = 90.0
	add_child(_storm)


func _rain_emitter(center: Vector3, extents: Vector3, count: int) -> void:
	var p := CPUParticles3D.new()
	p.amount = count
	p.lifetime = 1.1
	p.emission_shape = CPUParticles3D.EMISSION_SHAPE_BOX
	p.emission_box_extents = extents
	p.direction = Vector3(0.22, -1.0, 0.0)
	p.spread = 2.0
	p.initial_velocity_min = 23.0
	p.initial_velocity_max = 29.0
	p.gravity = Vector3.ZERO
	var streak := BoxMesh.new()
	streak.size = Vector3(0.014, 0.5, 0.014)
	var sm := StandardMaterial3D.new()
	sm.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	sm.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	sm.albedo_color = Color(0.65, 0.75, 0.95, 0.4)
	streak.material = sm
	p.draw_pass_1 = streak
	p.position = center
	add_child(p)


func _build_weather() -> void:
	_rain_emitter(Vector3(46.0, 13.0, -1.0), Vector3(62.0, 1.5, 7.0), 470)
	_rain_emitter(Vector3(129.0, 15.0, -1.0), Vector3(24.0, 1.5, 7.0), 260)
	# lightning wash sheet high behind the skyline
	_flash_quad = MeshInstance3D.new()
	var q := QuadMesh.new()
	q.size = Vector2(260.0, 130.0)
	_flash_quad.mesh = q
	_flash_quad.material_override = _mats["flash"]
	_flash_quad.position = Vector3(68.0, 45.0, -58.0)
	add_child(_flash_quad)


func _process(delta: float) -> void:
	# twin siren blink
	_siren_t += delta
	if _siren_red != null:
		var red_on := fposmod(_siren_t * 2.6, 2.0) < 1.0
		_siren_red.visible = red_on
		_siren_blue.visible = not red_on
		_siren_light.light_color = Color(1.0, 0.12, 0.12) if red_on else Color(0.15, 0.35, 1.0)
	# lightning
	_bolt_timer -= delta
	if _bolt_timer <= 0.0:
		_bolt_timer = randf_range(6.0, 13.0)
		_flash = randf_range(0.35, 0.6)
	if _flash > 0.0:
		_flash = maxf(_flash - delta, 0.0)
		var flicker := 0.6 + 0.4 * sin(_flash * 71.0)
		_storm.light_energy = 0.35 + _flash * 9.0 * flicker
		(_mats["flash"] as StandardMaterial3D).albedo_color.a = _flash * 0.55
	# flatline trace
	if _ecg_t >= 0.0:
		_ecg_t += delta
		var v := _ecg_sample(_ecg_t)
		_ecg_vals.append(v)
		if _ecg_vals.size() > 240:
			_ecg_vals.remove_at(0)
		_redraw_ecg()


# -------------------------------------------------- parallax backdrop ----
func _parallax(stick: float, pos: Vector3) -> Node3D:
	var p := Node3D.new()
	p.set_script(PARALLAX)
	p.set("stick", stick)
	p.position = pos
	add_child(p)
	return p


func _quad(parent: Node3D, mat: Material, x: float, y: float, w: float, h: float, z: float, flip_x := false) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var qm := QuadMesh.new()
	qm.size = Vector2(w, h)
	mi.mesh = qm
	mi.material_override = mat
	mi.position = Vector3(x, y, z)
	if flip_x:
		mi.scale.x = -1.0
	parent.add_child(mi)
	return mi


func _build_parallax_backdrop() -> void:
	var sky := _parallax(0.93, Vector3(70.0, 42.0, -62.0))
	_quad(sky, _mats["sky"], 0.0, 0.0, 330.0, 130.0, 0.0)
	var far := _parallax(0.72, Vector3(70.0, 14.5, -44.0))
	_quad(far, _mats["far"], -95.0, 0.0, 170.0, 31.9, 0.0)
	_quad(far, _mats["far"], 80.0, 0.0, 170.0, 31.9, 0.0, true)
	_quad(far, _mats["far"], 235.0, 0.0, 170.0, 31.9, 0.0)
	var mid := _parallax(0.50, Vector3(70.0, 12.4, -27.0))
	_quad(mid, _mats["mid"], -66.0, 0.0, 130.0, 28.4, 0.0)
	_quad(mid, _mats["mid"], 66.0, 0.0, 130.0, 28.4, 0.0, true)
	_quad(mid, _mats["mid"], 196.0, 0.0, 130.0, 28.4, 0.0)


# ------------------------------------------------------------ geometry ----
func _slab(x0: float, x1: float, top: float, h: float, d: float, mat: Material, zc := 0.0) -> StaticBody3D:
	var w := x1 - x0
	var b := StaticBody3D.new()
	var cs := CollisionShape3D.new()
	var shape := BoxShape3D.new()
	shape.size = Vector3(w, h, d)
	cs.shape = shape
	b.add_child(cs)
	var mi := MeshInstance3D.new()
	var mesh := BoxMesh.new()
	mesh.size = Vector3(w, h, d)
	mi.mesh = mesh
	mi.material_override = mat
	b.add_child(mi)
	b.position = Vector3((x0 + x1) * 0.5, top - h * 0.5, zc)
	add_child(b)
	return b


const STREET_RUNS := [[-10.0, 56.0], [59.0, 112.0]]  # street continues under the scaffold

func _build_street() -> void:
	for run in STREET_RUNS:
		var x0: float = run[0]
		var x1: float = run[1]
		_slab(x0, x1, 0.0, 1.0, 4.0, _mats["asphalt"])
		_slab(x0, x1, 0.07, 0.14, 1.7, _mats["brick"], -1.15)
		_slab(x0, x1, -0.30, 0.14, 2.4, _mats["asphalt"], 3.1)
	_slab(55.8, 59.2, -2.2, 0.3, 4.0, _mats["dark"])  # pit guts
	# continuous brick backs: buildings pressed against the playfield
	_wall(-10.0, 16.0, 7.0)
	_wall(16.0, 34.0, 6.0)
	_wall(34.0, 52.0, 8.0)
	_wall(52.0, 84.0, 7.5)
	_wall(84.0, 104.0, 6.5)
	_wall(104.0, 112.0, 6.5)  # backs the street behind the gate
	# solid ends: nowhere to run but forward
	_slab(-11.0, -10.0, 8.0, 8.0, 4.0, _mats["brick"])


func _wall(x0: float, x1: float, h: float) -> void:
	_slab(x0, x1, h, h, 0.6, _mats["brick"], -1.95)
	# sparse lit windows: somebody is always watching
	var rng := 0
	for wx in range(int(x0) + 2, int(x1) - 1, 3):
		rng += 1
		for wy in [2.8, 4.4]:
			if (rng + int(wy)) % 3 == 0:
				_quad(self, _mats["win_lit"], wx, wy, 0.55, 0.75, -1.62)
			else:
				_quad(self, _mats["win_dark"], wx, wy, 0.55, 0.75, -1.62)


# -------------------------------------------------------------- SEGMENT 1 -
func _build_s1_alley() -> void:
	# dumpster hop: first jump of the game
	_slab(6.4, 7.8, 1.1, 1.1, 1.4, _mats["steel"], -0.7)
	_slab(8.2, 9.0, 0.65, 0.65, 0.9, _mats["sand"], -0.6)
	# the half-dropped SHUTTER: only a crawl (CTRL) gets you through
	_slab(12.3, 14.1, 3.2, 2.15, 4.0, _mats["shutter"], 0.0)
	_quad(self, _glow(Color(0.9, 0.2, 0.1)), 13.2, 1.12, 1.6, 0.07, 0.05)  # warning strip
	# siren pole: red/blue chasing across the wet bricks
	var pole := MeshInstance3D.new()
	var pm := CylinderMesh.new()
	pm.top_radius = 0.06
	pm.bottom_radius = 0.08
	pm.height = 5.2
	pole.mesh = pm
	pole.material_override = _mats["steel"]
	pole.position = Vector3(-6.5, 2.6, -1.4)
	add_child(pole)
	_siren_red = MeshInstance3D.new()
	var s1 := SphereMesh.new()
	s1.radius = 0.16
	s1.height = 0.32
	_siren_red.mesh = s1
	_siren_red.material_override = _mats["siren_r"]
	_siren_red.position = Vector3(-6.72, 5.3, -1.4)
	add_child(_siren_red)
	_siren_blue = MeshInstance3D.new()
	_siren_blue.mesh = s1
	_siren_blue.material_override = _mats["siren_b"]
	_siren_blue.position = Vector3(-6.28, 5.3, -1.4)
	add_child(_siren_blue)
	_siren_light = OmniLight3D.new()
	_siren_light.light_energy = 2.2
	_siren_light.omni_range = 14.0
	_siren_light.position = Vector3(-6.5, 5.2, -0.8)
	add_child(_siren_light)


# -------------------------------------------------------------- SEGMENT 2 -
func _build_s2_dojo() -> void:
	# sandwich shop awning + crates: a small brawling pit
	_slab(18.0, 20.4, 2.05, 0.22, 1.2, _mats["steel"], -1.0)
	_slab(26.0, 26.9, 0.8, 0.8, 0.8, _mats["sand"], -0.6)
	_slab(27.0, 27.7, 1.5, 1.5, 0.7, _mats["sand"], -0.65)
	_slab(31.5, 33.9, 2.05, 0.22, 1.2, _mats["steel"], -1.0)


# -------------------------------------------------------------- SEGMENT 3 -
func _car(x0: float, x1: float, van := false) -> void:
	var w := x1 - x0
	var body_h := 2.0 if van else 0.85
	_slab(x0, x1, body_h, body_h, 1.8, _mats["steel"], -0.4)
	if not van:
		_slab(x0 + w * 0.25, x1 - w * 0.2, 1.45, 0.6, 1.5, _mats["dark"], -0.45)
	# wheels
	var wg := CylinderMesh.new()
	wg.top_radius = 0.32
	wg.bottom_radius = 0.32
	wg.height = 0.24
	for wx in [x0 + 0.7, x1 - 0.7]:
		for wz in [0.45, -1.25]:
			var wheel := MeshInstance3D.new()
			wheel.mesh = wg
			wheel.material_override = _mats["dark"]
			wheel.rotation.x = PI * 0.5
			wheel.position = Vector3(wx, 0.32, wz)
			add_child(wheel)


func _build_s3_traffic() -> void:
	_car(37.0, 40.2)          # sedan: vault it to flank the shield
	_car(44.0, 48.6, true)    # box van
	_quad(self, _glow(Color(1.0, 0.85, 0.4)), 37.05, 0.55, 0.06, 0.18, 0.56)
	_quad(self, _glow(Color(0.9, 0.1, 0.1)), 40.15, 0.55, 0.06, 0.18, 0.56)


# -------------------------------------------------------------- SEGMENT 4 -
func _build_s4_denial() -> void:
	# the canopy route OVER the smoke: dumpster step -> awning hops
	_slab(51.4, 52.8, 1.1, 1.1, 1.4, _mats["steel"], -0.7)
	var canopies := [[53.0, 55.5], [59.2, 62.0], [64.0, 66.8], [68.6, 71.4], [73.2, 76.0], [77.8, 80.6]]
	for c in canopies:
		_slab(c[0], c[1], 2.15, 0.22, 1.3, _mats["shutter"], -0.5)
		_slab(c[0] + 0.15, c[0] + 0.3, 2.15, 2.15, 0.16, _mats["dark"], -1.05)  # posts
	# street furniture the smoke rolls around
	_slab(69.4, 70.3, 0.8, 0.8, 0.9, _mats["sand"], -0.6)
	_slab(81.6, 83.4, 2.05, 0.22, 1.2, _mats["steel"], -1.0)


# -------------------------------------------------------------- SEGMENT 5 -
func _barrier(x: float) -> void:
	_slab(x, x + 0.14, 1.05, 1.05, 0.5, _mats["steel"], -0.2)
	_slab(x + 1.16, x + 1.3, 1.05, 1.05, 0.5, _mats["steel"], -0.2)
	for i in 3:
		var mat: Material = _mats["barrier_r"] if i % 2 == 0 else _mats["barrier_w"]
		_slab(x, x + 1.3, 1.02 - i * 0.2, 0.18, 0.42, mat, -0.2)


func _build_s5_barricade() -> void:
	# sandbag nests
	_slab(86.0, 88.2, 0.55, 0.55, 1.6, _mats["sand"], -0.3)
	_slab(86.4, 87.8, 1.0, 0.45, 1.3, _mats["sand"], -0.35)
	_slab(98.0, 100.2, 0.55, 0.55, 1.6, _mats["sand"], -0.3)
	_barrier(90.0)
	_barrier(93.5)
	# THE GATE: steel slab wall; sinks into the street when the squad falls
	_gate = _slab(104.0, 105.3, 4.4, 4.4, 4.0, _mats["shutter"], 0.0)
	for i in 4:  # hazard chevrons
		var mat: Material = _mats["barrier_r"] if i % 2 == 0 else _mats["barrier_w"]
		_quad(self, mat, 104.65, 0.5 + i * 1.0, 1.15, 0.24, 0.06)
	var lamp_post := MeshInstance3D.new()
	var lp := CylinderMesh.new()
	lp.top_radius = 0.05
	lp.bottom_radius = 0.05
	lp.height = 1.0
	lamp_post.mesh = lp
	lamp_post.material_override = _mats["steel"]
	lamp_post.position = Vector3(104.65, 4.9, -0.6)
	add_child(lamp_post)
	_gate_lamp = MeshInstance3D.new()
	var gs := SphereMesh.new()
	gs.radius = 0.14
	gs.height = 0.28
	_gate_lamp.mesh = gs
	_gate_lamp.material_override = _mats["siren_r"]
	_gate_lamp.position = Vector3(104.65, 5.5, -0.6)
	add_child(_gate_lamp)


# ------------------------------------------------- scaffold + rooftop ----
func _build_scaffold_and_roof() -> void:
	# zigzag scaffold ledges behind the gate
	_slab(105.8, 107.4, 2.2, 0.28, 1.2, _mats["steel"], -0.4)
	_slab(109.0, 110.6, 4.4, 0.28, 1.2, _mats["steel"], -0.4)
	_slab(106.4, 108.0, 6.6, 0.28, 1.2, _mats["steel"], -0.4)
	_slab(109.6, 111.6, 8.8, 0.28, 1.2, _mats["steel"], -0.4)
	# THE ROOFTOP (y = 10)
	_slab(112.0, 146.0, 10.0, 2.0, 6.0, _mats["roof"], 0.0)
	# backstop wall: the Raven's rush eats brick
	_slab(146.0, 147.2, 16.0, 8.0, 6.0, _mats["brick"], 0.0)
	# left safety fence: the player hops it, the boss's rush does not
	_slab(116.2, 116.5, 11.25, 1.25, 0.35, _mats["steel"], -0.1)
	# girders: the ONLY safe floor when the sweep grid fires (walkable, y=12)
	_slab(120.0, 127.0, 12.0, 0.35, 1.0, _mats["steel"], -0.2)
	_slab(133.0, 140.0, 12.0, 0.35, 1.0, _mats["steel"], -0.2)
	for gx in [120.2, 126.8, 133.2, 139.8]:  # hanger struts to the ceiling void
		_slab(gx, gx + 0.14, 12.0, 2.0, 0.14, _mats["dark"], -0.2)
	# rooftop dressing: tank, ACs, antenna, parapet lip
	var tank := MeshInstance3D.new()
	var tm := CylinderMesh.new()
	tm.top_radius = 0.85
	tm.bottom_radius = 0.85
	tm.height = 1.7
	tank.mesh = tm
	tank.material_override = _mats["steel"]
	tank.position = Vector3(121.5, 11.15, -1.9)
	add_child(tank)
	_slab(126.0, 127.4, 11.1, 1.1, 1.2, _mats["steel"], -1.6)
	_slab(137.6, 139.0, 11.1, 1.1, 1.2, _mats["steel"], -1.6)
	_slab(143.4, 143.7, 14.2, 4.2, 0.2, _mats["dark"], -1.9)
	_slab(112.0, 146.0, 10.55, 0.55, 0.3, _mats["dark"], -2.85)
	# floodlight towers with fake volumetric cones + real omnis
	for fx in [118.5, 141.5]:
		var post := MeshInstance3D.new()
		var fm := CylinderMesh.new()
		fm.top_radius = 0.07
		fm.bottom_radius = 0.1
		fm.height = 5.4
		post.mesh = fm
		post.material_override = _mats["steel"]
		post.position = Vector3(fx, 12.7, -2.2)
		add_child(post)
		var head := MeshInstance3D.new()
		var hb := BoxMesh.new()
		hb.size = Vector3(0.6, 0.34, 0.3)
		head.mesh = hb
		head.material_override = _mats["lamp_head"]
		head.position = Vector3(fx, 15.4, -2.1)
		add_child(head)
		var cone := MeshInstance3D.new()
		var cm := CylinderMesh.new()
		cm.top_radius = 0.25
		cm.bottom_radius = 2.4
		cm.height = 5.2
		cone.mesh = cm
		cone.material_override = _mats["cone"]
		cone.position = Vector3(fx, 12.7, -1.9)
		add_child(cone)
		var omni := OmniLight3D.new()
		omni.light_color = Color(1.0, 0.82, 0.5)
		omni.light_energy = 1.6
		omni.omni_range = 11.0
		omni.position = Vector3(fx, 15.2, -1.6)
		add_child(omni)


# ------------------------------------------------------------- gameplay ---
func _spawn_enemy_script(script: Script, x: float, y_surface: float, min_x: float, max_x: float, tint: Color, aggr := 1.0) -> Node3D:
	var e := ENEMY.instantiate()
	e.set_script(script)
	e.set("patrol_min_x", min_x)
	e.set("patrol_max_x", max_x)
	e.set("base_tint", tint)
	e.set("aggression", aggr)
	e.position = Vector3(x, y_surface + 0.9, 0.0)  # BEFORE add_child: spawn cache
	add_child(e)
	return e


func _spawn_typed(scene_script: Script, x: float, min_x: float, max_x: float, tint: Color) -> Node3D:
	return _spawn_enemy_script(scene_script, x, 0.0, min_x, max_x, tint)


func _track_squad(e: Node3D) -> void:
	_squad_alive += 1
	var h: Node = e.get_node_or_null("Health")
	if h != null:
		h.died.connect(_on_squad_died)


func _on_squad_died() -> void:
	_squad_alive -= 1
	if _squad_alive <= 0 and not _outro_started:
		_breach_gate()


func _breach_gate() -> void:
	if _gate == null:
		return
	_gate_lamp.material_override = _mats["gate_g"]
	var ih := get_node_or_null("/root/InputHelper")
	if ih != null and ih.has_method("rumble_medium"):
		ih.rumble_medium()  # the street shakes as the gate sinks
	var tw := create_tween()
	tw.tween_property(_gate, "position:y", _gate.position.y - 4.6, 1.6) \
		.set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_IN)
	tw.tween_callback(_gate.queue_free)


func _build_gameplay() -> void:
	_tito = TITO.instantiate()
	_tito.position = Vector3(-7.0, 1.2, 0.0)
	add_child(_tito)

	# checkpoints: after the shutter / before denial / after the gate
	_spawn_scene(CHECKPOINT, Vector3(16.5, 0.75, 0.0))
	_spawn_scene(CHECKPOINT, Vector3(52.0, 0.75, 0.0))
	_spawn_scene(CHECKPOINT, Vector3(106.6, 0.75, 0.0))
	# the pit between denial canopies
	_spawn_scene(DEATHZONE, Vector3(56.9, -1.2, 0.0))
	_spawn_scene(DEATHZONE, Vector3(58.1, -1.2, 0.0))

	# S2 — light thugs (punch tutorial)
	var thug := Color(0.22, 0.26, 0.42)
	_spawn_enemy_script(TitoEnemy, 22.0, 0.0, 18.0, 28.0, thug)
	_spawn_enemy_script(TitoEnemy, 30.0, 0.0, 26.0, 33.0, thug)
	# S3 — shield enforcer holding the traffic jam
	_spawn_typed(SHIELD, 46.0, 40.0, 50.0, Color(0.18, 0.19, 0.24))
	# S4 — area denial: smoke support + red-line marksman
	_spawn_typed(LAUNCHER, 76.0, 73.0, 82.0, Color(0.32, 0.34, 0.24))
	_spawn_typed(AGENT, 80.0, 74.0, 83.0, Color(0.24, 0.24, 0.3))
	# S5 — the gate squad (all three must fall)
	_track_squad(_spawn_enemy_script(TitoEnemy, 89.0, 0.0, 85.0, 95.0, thug))
	_track_squad(_spawn_enemy_script(TitoEnemy, 93.0, 0.0, 88.0, 98.0, thug))
	_track_squad(_spawn_typed(AGENT, 96.0, 92.0, 101.0, Color(0.24, 0.24, 0.3)))

	# EL-GHORAB waits on the roof, coat snapping in the storm
	_boss = GhorabBoss.new()
	_boss.arena_min_x = ARENA_MIN
	_boss.arena_max_x = ARENA_MAX
	_boss.sweep_safe_y = 11.5
	_boss.position = Vector3(136.0, 10.15, 0.0)
	add_child(_boss)
	_boss.boss_died.connect(_on_boss_died)

	# cinematic tripwire at the roof's mouth
	var trig := Area3D.new()
	trig.collision_layer = 0
	trig.collision_mask = 2
	var tcs := CollisionShape3D.new()
	var tbox := BoxShape3D.new()
	tbox.size = Vector3(1.2, 3.4, 4.0)
	tcs.shape = tbox
	trig.add_child(tcs)
	trig.position = Vector3(119.0, 11.6, 0.0)
	add_child(trig)
	trig.body_entered.connect(_on_intro_body)


func _spawn_scene(scene: PackedScene, pos: Vector3, props := {}) -> Node3D:
	var n := scene.instantiate()
	for k in props.keys():
		n.set(k, props[k])
	n.position = pos
	add_child(n)
	return n


# ---------------------------------------------------------------- labels --
var _hints: Array = []  # [Label3D, kb_text, xbox_text, ps_text]


func _label(text: String, pos: Vector3, size: int, tint: Color) -> Label3D:
	var l := Label3D.new()
	l.text = text
	l.font = load(FONT_BOLD) as Font
	l.font_size = size
	l.modulate = tint
	l.outline_size = max(8, size / 8)
	l.outline_modulate = Color(0, 0, 0, 0.85)
	l.position = pos
	add_child(l)
	return l


## Hint label that rewords itself when the player swaps keyboard <-> gamepad
## (Input Helper autoload does the device detection; we just listen).
func _hint_label(kb: String, xb: String, ps: String, pos: Vector3, size: int, tint: Color) -> void:
	var l := _label(kb, pos, size, tint)
	_hints.append([l, kb, xb, ps])


func _refresh_hints(device: String) -> void:
	for h in _hints:
		match device:
			"xbox", "switch", "steamdeck", "generic":
				(h[0] as Label3D).text = h[2]
			"playstation":
				(h[0] as Label3D).text = h[3]
			_:
				(h[0] as Label3D).text = h[1]


func _refresh_hints_unbound(device: String, _index: int) -> void:
	_refresh_hints(device)


func _setup_device_hints() -> void:
	var ih: Node = get_node_or_null("/root/InputHelper")
	if ih == null:
		return
	ih.device_changed.connect(_refresh_hints_unbound)
	_refresh_hints(str(ih.get("device")))


func _build_labels() -> void:
	_label("الهروب — ليلة البداية", Vector3(-7.0, 3.6, -0.6), 120, Color(1.0, 0.8, 0.5))
	_hint_label("A/D حركة · SPACE قفز · J ضرب · CTRL زحف",
		"عصا شمال حركة · A قفز · X ضرب · B زحف",
		"عصا شمال حركة · إكس قفز · مربع ضرب · دايرة زحف",
		Vector3(-7.0, 2.6, -0.6), 52, Color(0.7, 0.8, 1.0))
	_hint_label("اتزحلق تحت الشتر: CTRL", "اتزحلق تحت الشتر: B", "اتزحلق تحت الشتر: دايرة",
		Vector3(12.0, 3.8, -0.5), 60, Color(1.0, 0.85, 0.5))
	_hint_label("اضرب: J", "اضرب: X", "اضرب: مربع",
		Vector3(21.0, 3.2, -0.5), 64, Color(1.0, 0.85, 0.5))
	_label("الدرع بيصد من قدام — ادخل من وراه!", Vector3(45.0, 4.2, -0.5), 56, Color(1.0, 0.6, 0.4))
	_label("الدخان بيحرق.. كمّل فوق المظلات!", Vector3(63.0, 4.6, -0.5), 56, Color(0.75, 0.9, 1.0))
	_hint_label("الخط الأحمر = انزل على الأرض: CTRL", "الخط الأحمر = انزل على الأرض: B", "الخط الأحمر = انزل على الأرض: دايرة",
		Vector3(76.0, 4.6, -0.5), 52, Color(1.0, 0.55, 0.45))
	_label("اقضي على الفرقة عشان البوابة تفتح", Vector3(92.0, 4.8, -0.5), 56, Color(1.0, 0.85, 0.5))
	_label("السطح فوق — الحديد هو أمانك من المسح", Vector3(117.0, 13.4, -0.5), 48, Color(0.8, 0.85, 1.0))
	_setup_device_hints()


# ------------------------------------------------------ cinematic overlay -
func _full_rect(c: Color) -> ColorRect:
	var r := ColorRect.new()
	r.color = c
	r.set_anchors_preset(Control.PRESET_FULL_RECT)
	return r


func _build_cinematic_overlay() -> void:
	_cine = CanvasLayer.new()
	_cine.layer = 20
	add_child(_cine)
	# full-screen flashes FIRST so dialogue text always draws above them
	_white = _full_rect(Color(1, 1, 1, 0))
	_white.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_cine.add_child(_white)
	_black = _full_rect(Color(0, 0, 0, 0))
	_black.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_cine.add_child(_black)
	_cine_root = Control.new()
	_cine_root.set_anchors_preset(Control.PRESET_FULL_RECT)
	_cine_root.visible = false
	_cine.add_child(_cine_root)
	var top := _full_rect(Color.BLACK)
	top.anchor_bottom = 0.0
	top.offset_bottom = 86
	_cine_root.add_child(top)
	var bottom := _full_rect(Color.BLACK)
	bottom.anchor_top = 1.0
	bottom.offset_top = -150
	_cine_root.add_child(bottom)
	var font: Font = load(FONT_BOLD)
	_spk = Label.new()
	_spk.anchor_left = 0.08
	_spk.anchor_right = 0.92
	_spk.anchor_top = 1.0
	_spk.anchor_bottom = 1.0
	_spk.offset_top = -140
	_spk.offset_bottom = -104
	_spk.add_theme_font_override("font", font)
	_spk.add_theme_font_size_override("font_size", 26)
	_cine_root.add_child(_spk)
	_line_ar = Label.new()
	_line_ar.anchor_left = 0.06
	_line_ar.anchor_right = 0.94
	_line_ar.anchor_top = 1.0
	_line_ar.anchor_bottom = 1.0
	_line_ar.offset_top = -100
	_line_ar.offset_bottom = -54
	_line_ar.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_line_ar.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	_line_ar.add_theme_font_override("font", font)
	_line_ar.add_theme_font_size_override("font_size", 32)
	_line_ar.add_theme_color_override("font_color", Color(1.0, 0.95, 0.85))
	_cine_root.add_child(_line_ar)
	_line_en = Label.new()
	_line_en.anchor_left = 0.08
	_line_en.anchor_right = 0.92
	_line_en.anchor_top = 1.0
	_line_en.anchor_bottom = 1.0
	_line_en.offset_top = -50
	_line_en.offset_bottom = -8
	_line_en.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_line_en.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	_line_en.add_theme_font_override("font", font)
	_line_en.add_theme_font_size_override("font_size", 18)
	_line_en.add_theme_color_override("font_color", Color(0.62, 0.66, 0.78))
	_cine_root.add_child(_line_en)
	# the heart monitor (topmost)
	_ecg = Line2D.new()
	_ecg.default_color = Color(0.3, 1.0, 0.5)
	_ecg.width = 3.0
	_ecg.visible = false
	_cine.add_child(_ecg)


func _on_intro_body(body: Node3D) -> void:
	if _intro_done or _boss == null or not body.is_in_group("player"):
		return
	_intro_done = true
	_tito.set_physics_process(false)
	_tito.velocity = Vector3.ZERO
	_play_lines(LINES_INTRO, Callable(self, "_intro_finished"))


func _play_lines(lines: Array, on_done: Callable) -> void:
	_cine_root.visible = true
	for item in lines:
		_spk.text = item[0]
		_spk.add_theme_color_override("font_color", item[1])
		_line_ar.text = item[2]
		_line_en.text = item[3]
		await get_tree().create_timer(item[4]).timeout
	_cine_root.visible = false
	on_done.call()


func _intro_finished() -> void:
	if is_instance_valid(_tito):
		_tito.set_physics_process(true)
	if _boss != null:
		_boss.begin_fight()


# ------------------------------------------------------------- the outro --
func _on_boss_died(boss: GhorabBoss) -> void:
	if _outro_started:
		return
	_outro_started = true
	# the Raven falls
	var tw := create_tween().set_parallel()
	tw.tween_property(boss, "rotation:z", -PI * 0.5 * signf(boss.get("_dir")) if boss.get("_dir") != 0.0 else -PI * 0.5, 0.7) \
		.set_trans(Tween.TRANS_BOUNCE).set_ease(Tween.EASE_OUT)
	tw.tween_property(boss, "position:y", boss.position.y + 0.55, 0.7)
	_run_outro()


func _run_outro() -> void:
	if is_instance_valid(_tito):
		_tito.set_physics_process(false)
	await get_tree().create_timer(1.6).timeout
	# counter-strike from the dark: headlights, a single shot, then nothing
	var wt := create_tween()
	wt.tween_property(_white, "color:a", 1.0, 0.12)
	wt.tween_interval(0.18)
	wt.tween_property(_white, "color:a", 0.0, 0.5)
	await wt.finished
	await get_tree().create_timer(0.35).timeout
	_black.color = Color(0, 0, 0, 1)  # the shot
	await get_tree().create_timer(0.9).timeout
	# flatline
	_ecg_vals.clear()
	_ecg.visible = true
	_ecg_t = 0.0
	await get_tree().create_timer(7.0).timeout
	_ecg.visible = false
	# the rewind hook
	_play_lines(LINES_OUTRO, Callable(self, "_to_chapter_one"))


func _ecg_sample(t: float) -> float:
	if t > 2.6:
		return randf_range(-0.03, 0.03)  # flat
	var ph := fposmod(t, 0.86) / 0.86
	if ph < 0.06:
		return -0.35
	if ph < 0.14:
		return 1.0
	if ph < 0.22:
		return -0.28
	if ph < 0.3:
		return 0.12
	return 0.0


func _redraw_ecg() -> void:
	var vp := get_viewport().get_visible_rect().size
	var base_y := vp.y * 0.45
	var n := maxi(_ecg_vals.size(), 2)
	var pts := PackedVector2Array()
	for i in n:
		var x := vp.x * 0.5 - (n * 0.5 - i) * 4.0
		pts.append(Vector2(x, base_y - _ecg_vals[i] * 42.0))
	_ecg.points = pts


func _to_chapter_one() -> void:
	var tw := create_tween()
	tw.tween_property(_black, "color:a", 1.0, 0.8)
	await tw.finished
	get_tree().change_scene_to_file(CHAPTER_ONE)
